wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.11
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.9
    start_time: 1680603076.143845
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 16
      - 23
      4: 3.10.9
      5: 0.13.11
      8:
      - 3
      - 5
architecture:
  desc: null
  value: CNN_MobileNetV2
dataset:
  desc: null
  value: FSL_Resized
epochs:
  desc: null
  value: 20
learning_rate:
  desc: null
  value: 0.0001
optimizer:
  desc: null
  value: RMSProp
